services:
  pg:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3
  app:
    build:
      context: .
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg/${POSTGRES_DB}"
    depends_on:
      pg:
        condition: service_healthy
#    develop:
#      watch:
#        - action: rebuild
#          path: .
