version: '3.9'


services:
  db:
    image: postgres
#    ports:
#      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 6
  backend:
    build:
      context: .
#    ports:
#      - 8080:8080
    expose:
      - 8080
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    command: bash -c "
      python manage.py migrate
      && python manage.py fill_db
      && gunicorn zoo.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:80
